### ISSUE TITLE
Changing the license

### ISSUE THREAD

**Issue by lij20** [jackstenglein/mui-mentions#2]
Thank you for your amazing work on this project! I noticed this package is GPL-licensed, which is quite unusual as most Node packages are MIT-licensed. Would you be open to changing the license to a more permissive one like MIT, BSD, or Apache? The more permissive licenses would still preserve credit to the original authors, but they're a lot easier to integrate into a wide variety of projects.

**Comment by jackstenglein** [comment]
Sure, I just changed it to MIT license

**Comment by lij20** [comment]
Thank you!!

**Comment by lij20** [comment]
If you're ever in need of a job, please let me know! My company is hiring :)
