### ISSUE TITLE
Multiline mentions are not correctly highlighted

### ISSUE THREAD

**Issue by jgomezgadea** [jackstenglein/mui-mentions#3]
With the multiline functionality, if the mentioned person's name is split across two lines, the highlight feature does not work correctly.
<img width="393" alt="Screenshot 2024-10-16 at 11 41 55" src="https://github.com/user-attachments/assets/ac711e7f-f5b9-43e4-958f-f01d3d69ce3f">

You can check out this video to see how to replicate the issue.

https://github.com/user-attachments/assets/2eb63797-5a75-47ab-a467-b85d7a0650f4

**Comment by jackstenglein** [comment]
@jgomezgadea This should be working now. By default, the spaces inside the mention are converted to no-break spaces when displayed in the textarea. This ensures that the mention is kept on a single line and the highlight displays correctly. If you've passed the `displayTransform` prop, you will need to add similar space replacement logic there.
