### ISSUE TITLE
License outdated in package.json

### ISSUE THREAD

**Issue by baldoalessandro** [jackstenglein/mui-mentions#4]
I've seen that you changed the license of the project from GPL to MIT here #2 
This change was not reflected in the license field inside the `package.json` here:
https://github.com/jackstenglein/mui-mentions/blob/43047c70edfb9a997de447a669548ea09454c81b/package.json#L32

This shows the wrong information in npm.js page https://www.npmjs.com/package/@jackstenglein/mui-mentions which could, potentially, deter people from using this awesome library :disappointed:

**Comment by jackstenglein** [comment]
Thanks for the PR!
